import app from "./teaching_mode_worker.js";

const STATE_KEY = "global";
const MAX_COMMANDS_SHOWN = 20;

function constantTimeEqual(a,b){a=String(a||"");b=String(b||"");if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
function authOK(request,env){const p=String(env.LUMEN_DASHBOARD_PASSWORD||"");if(!p)return null;const h=request.headers.get("Authorization")||"";if(!h.startsWith("Basic "))return false;try{const x=atob(h.slice(6));const i=x.indexOf(":");if(i<0)return false;return constantTimeEqual(x.slice(0,i),String(env.LUMEN_DASHBOARD_USER||"socio"))&&constantTimeEqual(x.slice(i+1),p);}catch{return false;}}
function unauthorized(){return new Response("LUMEN · acceso restringido",{status:401,headers:{"WWW-Authenticate":'Basic realm="LUMEN Centro de Comando", charset="UTF-8"',"Cache-Control":"no-store"}});}
function locked(){return new Response("LUMEN dashboard todavía no tiene contraseña configurada.",{status:503,headers:{"Cache-Control":"no-store"}});}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});}
async function sha256Hex(bytes){const hash=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("");}
async function loadState(env){const m=await env.DB.prepare("SELECT encoding,chunk_count,payload_sha256,uncompressed_bytes,updated_at FROM lumen_state_manifest WHERE state_key=? LIMIT 1").bind(STATE_KEY).first();if(!m)throw new Error("state_not_initialized");const r=await env.DB.prepare("SELECT chunk_no,payload FROM lumen_state_chunks WHERE state_key=? ORDER BY chunk_no ASC").bind(STATE_KEY).all();const chunks=r.results||[];if(chunks.length!==Number(m.chunk_count||0))throw new Error("incomplete_state_chunks");const enc=chunks.map(x=>String(x.payload||"")).join("");const bin=atob(enc);const compressed=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)compressed[i]=bin.charCodeAt(i);const stream=new Blob([compressed]).stream().pipeThrough(new DecompressionStream("deflate"));const raw=new Uint8Array(await new Response(stream).arrayBuffer());if(m.payload_sha256&&await sha256Hex(raw)!==m.payload_sha256)throw new Error("state_checksum_mismatch");return {state:JSON.parse(new TextDecoder().decode(raw)),manifest:m};}

async function ensureSchema(env){await env.DB.prepare("CREATE TABLE IF NOT EXISTS lumen_owner_decision_commands (command_id TEXT PRIMARY KEY, decision_key TEXT NOT NULL UNIQUE, action TEXT NOT NULL, decision_type TEXT NOT NULL, object_id TEXT, actor TEXT NOT NULL, scope TEXT NOT NULL, payload_json TEXT, created_at TEXT NOT NULL, processed INTEGER NOT NULL DEFAULT 0, processed_at TEXT, result TEXT)").run();await env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_lumen_owner_decision_pending ON lumen_owner_decision_commands(processed, created_at)").run();}

function decisionCandidates(state){const out=[];const ledger=Array.isArray(state?.improvement_ledger)?state.improvement_ledger:[];for(const row of ledger){if(!row||String(row.status||"").toUpperCase()!=="HUMAN_REVIEW_REQUIRED")continue;const id=String(row.id||"").trim();if(!id)continue;out.push({decision_key:`learning:${id}`,decision_type:"self_improvement",object_id:id,code:String(row.code||"SELF-IMPROVEMENT"),title:String(row.hypothesis||row.change_proposed||row.code||"Mejora propuesta"),reason:String(row.problem||"LUMEN propone una mejora que requiere revisión humana."),evidence:row.evidence||{},confidence:Number(row.confidence||0),samples:Number(row.samples||0),risk:row.code_change_required?"medium":"low",scope:"BUILD_TEST_ONLY",recommendation:"Aprobar habilita construcción y pruebas. No autoriza despliegue productivo, gasto, contratos ni cambios de autoridad.",created_at:row.created_at||null,updated_at:row.updated_at||null});}
return out.sort((a,b)=>(b.updated_at||"").localeCompare(a.updated_at||""));}

async function resolvedMap(env){await ensureSchema(env);const r=await env.DB.prepare("SELECT command_id,decision_key,action,decision_type,object_id,actor,scope,created_at,processed,processed_at,result FROM lumen_owner_decision_commands ORDER BY created_at DESC LIMIT ?").bind(MAX_COMMANDS_SHOWN).all();const rows=r.results||[];return {rows,map:new Map(rows.map(x=>[String(x.decision_key||""),x]))};}

async function getDecisions(env){const [{state,manifest},{rows,map}]=await Promise.all([loadState(env),resolvedMap(env)]);const candidates=decisionCandidates(state);const pending=candidates.filter(x=>!map.has(x.decision_key));return {ok:true,status:pending.length?"ACTION_REQUIRED":"CLEAR",pending,resolved:rows,counts:{pending:pending.length,resolved:rows.length},state_updated_at:manifest.updated_at||null,guardrails:{approval_scope:"build_and_test_only_for_code_changes",production_deploy:false,autonomous_spend_usd:0,binding_contracts:false,authority_change:false}};}

async function recordDecision(request,env){let body={};try{body=await request.json();}catch{return json({ok:false,error:"invalid_json"},400);}const decisionKey=String(body.decision_key||"").trim();const action=String(body.action||"").trim().toLowerCase();if(!decisionKey||!["approve","reject"].includes(action))return json({ok:false,error:"invalid_decision"},400);await ensureSchema(env);const existing=await env.DB.prepare("SELECT decision_key,action,scope,created_at,processed,result FROM lumen_owner_decision_commands WHERE decision_key=? LIMIT 1").bind(decisionKey).first();if(existing)return json({ok:true,status:"ALREADY_DECIDED",decision:existing});const {state}=await loadState(env);const candidate=decisionCandidates(state).find(x=>x.decision_key===decisionKey);if(!candidate)return json({ok:false,error:"decision_not_active_or_stale"},409);const commandId=`OWNER-${crypto.randomUUID()}`;const now=new Date().toISOString();const payload=JSON.stringify({code:candidate.code,title:candidate.title,reason:candidate.reason,evidence:candidate.evidence,confidence:candidate.confidence,samples:candidate.samples,risk:candidate.risk,recommendation:candidate.recommendation});try{await env.DB.prepare("INSERT INTO lumen_owner_decision_commands(command_id,decision_key,action,decision_type,object_id,actor,scope,payload_json,created_at,processed) VALUES(?,?,?,?,?,?,?,?,?,0)").bind(commandId,decisionKey,action,candidate.decision_type,candidate.object_id,"authenticated_dashboard_owner",candidate.scope,payload,now).run();}catch(error){const race=await env.DB.prepare("SELECT decision_key,action,scope,created_at,processed,result FROM lumen_owner_decision_commands WHERE decision_key=? LIMIT 1").bind(decisionKey).first();if(race)return json({ok:true,status:"ALREADY_DECIDED",decision:race});throw error;}return json({ok:true,status:action==="approve"?"APPROVAL_RECORDED":"REJECTION_RECORDED",decision_key:decisionKey,action,scope:candidate.scope,guardrails:{production_deploy:false,autonomous_spend_usd:0,binding_contracts:false,authority_change:false},message:action==="approve"?"Aprobación registrada. LUMEN puede construir y probar; producción sigue protegida por sus gates.":"Propuesta desestimada y registrada para el próximo ciclo de aprendizaje."},202);}

const DECISION_CSS=`<style id="lumen-decision-css">
.decision-center{margin:12px 0;background:linear-gradient(180deg,#151b12,#0b1515);border:1px solid #506536;border-radius:16px;padding:14px;box-shadow:0 14px 35px #0003}.dc-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.dc-title{font-size:17px;font-weight:950}.dc-sub{color:#9fb2aa;font-size:12px;line-height:1.5;margin-top:4px}.dc-count{background:#d9ff65;color:#061019;border-radius:999px;padding:6px 10px;font-weight:950;white-space:nowrap}.dc-list{display:grid;gap:10px;margin-top:12px}.dc-card{background:#081419;border:1px solid #29453d;border-radius:12px;padding:12px}.dc-row{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.dc-code{font:11px ui-monospace,SFMono-Regular,Menlo,monospace;color:#83d9ff}.dc-name{font-weight:900;margin:4px 0}.dc-reason,.dc-meta{color:#9fb2aa;font-size:12px;line-height:1.45}.dc-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.dc-btn{border-radius:9px;padding:9px 12px;font-weight:900;cursor:pointer}.dc-approve{border:0;background:#d9ff65;color:#061019}.dc-reject{border:1px solid #75453f;background:#241414;color:#ffb2aa}.dc-detail{border:1px solid #315060;background:#0c1d27;color:#d9edf5}.dc-btn:disabled{opacity:.5;cursor:wait}.dc-ok{color:#9de8c5}.dc-warn{color:#ffd36e}.dc-empty{color:#9de8c5;padding:9px 0;font-weight:800}@media(max-width:650px){.decision-center{padding:11px}.dc-head,.dc-row{display:block}.dc-count{display:inline-block;margin-top:8px}}
</style>`;

const DECISION_HTML=`<section class="decision-center" id="lumen-decision-center"><div class="dc-head"><div><div class="dc-title">Centro de Decisiones</div><div class="dc-sub">LUMEN te trae sólo las decisiones que requieren autoridad humana. Aprobar código habilita construir y probar; nunca despliega, gasta ni firma por sí solo.</div></div><div class="dc-count" id="dcCount">…</div></div><div class="dc-list" id="dcList"><div class="dc-meta">Cargando decisiones…</div></div></section>`;

const DECISION_SCRIPT=`<script id="lumen-decision-script">
(()=>{const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const count=document.getElementById('dcCount'),list=document.getElementById('dcList');async function call(url,opts={}){const r=await fetch(url,{cache:'no-store',...opts});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{throw new Error('Respuesta inválida')}if(!r.ok||d.ok===false)throw new Error(d.error||('HTTP '+r.status));return d}function details(d){return '<details><summary class="dc-meta" style="cursor:pointer;margin-top:8px">Ver evidencia y alcance</summary><pre style="white-space:pre-wrap;word-break:break-word;font-size:11px;color:#9fb2aa">'+esc(JSON.stringify({evidence:d.evidence,confidence:d.confidence,samples:d.samples,recommendation:d.recommendation,scope:d.scope},null,2))+'</pre></details>'}function render(d){const rows=d.pending||[];count.textContent=rows.length+' pendiente'+(rows.length===1?'':'s');if(!rows.length){list.innerHTML='<div class="dc-empty">Sin decisiones pendientes. LUMEN puede seguir trabajando.</div>';return}list.innerHTML=rows.map(x=>'<div class="dc-card" data-key="'+esc(x.decision_key)+'"><div class="dc-row"><div><div class="dc-code">'+esc(x.code)+'</div><div class="dc-name">'+esc(x.title)+'</div><div class="dc-reason">'+esc(x.reason)+'</div></div><div class="dc-meta">Riesgo: '+esc(x.risk)+' · '+esc(x.samples)+' muestras</div></div>'+details(x)+'<div class="dc-actions"><button class="dc-btn dc-approve" data-action="approve">Aprobar</button><button class="dc-btn dc-reject" data-action="reject">Desestimar</button></div><div class="dc-meta" data-status></div></div>').join('')}async function load(){try{render(await call('/api/owner-decisions'))}catch(e){count.textContent='error';list.innerHTML='<div class="dc-warn">No pude cargar decisiones: '+esc(e.message||e)+'</div>'}}async function decide(card,action){const label=action==='approve'?'APROBAR':'DESESTIMAR';if(!confirm(label+' esta propuesta de LUMEN?'))return;const buttons=card.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);const status=card.querySelector('[data-status]');status.textContent='Registrando decisión…';try{const d=await call('/api/owner-decisions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({decision_key:card.dataset.key,action})});status.className='dc-meta dc-ok';status.textContent=d.message||'Decisión registrada.';setTimeout(load,600)}catch(e){status.className='dc-meta dc-warn';status.textContent='No se pudo registrar: '+String(e.message||e);buttons.forEach(b=>b.disabled=false)}}list?.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const card=b.closest('[data-key]');if(card)decide(card,b.dataset.action)});load();})();
</script>`;

function injectDecisionCenter(html){if(html.includes('id="lumen-decision-center"'))return html;if(!html.includes('</body>'))return html;html=html.replace('</head>',`${DECISION_CSS}</head>`);const anchors=['<main','<div class="wrap"'];let injected=false;for(const anchor of anchors){const i=html.indexOf(anchor);if(i>=0){const close=html.indexOf('>',i);if(close>=0){html=html.slice(0,close+1)+DECISION_HTML+html.slice(close+1);injected=true;break;}}}if(!injected)html=html.replace('<body>','<body>'+DECISION_HTML);html=html.replace('</body>',`${DECISION_SCRIPT}</body>`);return html;}

export default {
  async fetch(request,env,ctx){
    const auth=authOK(request,env);if(auth===null)return locked();if(auth===false)return unauthorized();
    const url=new URL(request.url);
    try{
      if(url.pathname==="/api/owner-decisions"&&request.method==="GET")return json(await getDecisions(env));
      if(url.pathname==="/api/owner-decisions"&&request.method==="POST")return await recordDecision(request,env);
    }catch(error){return json({ok:false,error:"decision_center_failed",detail:String(error?.message||error).slice(0,300)},500);}
    const response=await app.fetch(request.clone(),env,ctx);
    const isHtml=request.method==="GET"&&response.ok&&String(response.headers.get("content-type")||"").includes("text/html");
    if(!isHtml)return response;
    const html=injectDecisionCenter(await response.text());const headers=new Headers(response.headers);headers.delete("content-length");headers.set("cache-control","no-store, no-cache, must-revalidate");headers.set("x-lumen-decision-center","v1");return new Response(html,{status:response.status,statusText:response.statusText,headers});
  }
};
