name = "lumen-zero-cognitive-shadow"
main = "worker.js"
compatibility_date = "2026-09-21"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "lumen-zero"
database_id = "e872694a-ed14-4a7f-b2c3-38b8e1bb498b"

[[services]]
binding = "COGNITIVE"
service = "lumen-zero-cognitive"

[triggers]
crons = ["7 * * * *"]
