from __future__ import annotations
from datetime import datetime, timezone
from typing import Any, Dict
from canonical_revenue_truth_runtime import canonical_revenue_truth_tick
VERSION="1.2-causal-revenue-funnel-canonical"; MAX_HISTORY=96
def utcnow()->str:return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
def _realized(state:Dict[str,Any])->int:
    statuses={"realized","realized_partial","received","paid","settled","completed","collected"}; return sum(1 for x in state.get("revenue_ledger",[]) or [] if str(x.get("status") or "").lower() in statuses)
def _counts(state:Dict[str,Any],truth:Dict[str,Any])->Dict[str,int]:
    accounts=list(state.get("candidate_accounts",[]) or []); buyers=[x for x in accounts if x.get("type")=="buyer" and x.get("verified_company")]; contacts=[x for x in accounts if x.get("verified_company") and (x.get("commercial_channel_verified") or x.get("verified_contact"))]; c=truth.get("counts",{}) or {}; oppids=set(str(x) for x in truth.get("canonical_opportunity_ids",[]) or []); rfq=[x for x in state.get("interlocution_cases",[]) or [] if x.get("supplier_rfq_ready") and str(x.get("opportunity_id") or "") in oppids]
    return {"research_leads":len(state.get("research_leads",[]) or []),"verified_companies":sum(1 for x in accounts if x.get("verified_company")),"verified_contacts":len(contacts),"verified_buyers":len(buyers),"buyers_with_demand":int(c.get("buyers_with_verified_demand") or 0),"market_opportunities":int(c.get("canonical_opportunities") or 0),"raw_market_opportunities":int(c.get("raw_market_opportunities") or 0),"rfq_ready":len(rfq),"quotes":int(c.get("canonical_real_offers") or 0),"real_offers":int(c.get("canonical_real_offers") or 0),"proposals":int(c.get("canonical_proposals") or 0),"active_deals":int(c.get("canonical_active_deals") or 0),"raw_deals":int(c.get("raw_deals") or 0),"closing_eligible_deals":int(c.get("closing_eligible_deals") or 0),"close_ready":int(c.get("canonical_close_ready") or 0),"quarantined_deals":int(c.get("quarantined_deals") or 0),"realized_events":_realized(state)}
def _rate(n:int,d:int):return None if d<=0 else round(n/d*100.0,1)
def _rates(c:Dict[str,int])->Dict[str,Any]:return {"lead_to_verified_company_pct":_rate(c["verified_companies"],c["research_leads"]),"company_to_verified_contact_pct":_rate(c["verified_contacts"],c["verified_companies"]),"verified_buyer_to_demand_pct":_rate(c["buyers_with_demand"],c["verified_buyers"]),"demand_to_opportunity_pct":_rate(c["market_opportunities"],c["buyers_with_demand"]),"opportunity_to_rfq_ready_pct":_rate(c["rfq_ready"],c["market_opportunities"]),"opportunity_to_quote_pct":_rate(c["quotes"],c["market_opportunities"]),"quote_to_offer_pct":_rate(c["real_offers"],c["quotes"]),"offer_to_proposal_pct":_rate(c["proposals"],c["real_offers"]),"active_deal_to_close_ready_pct":_rate(c["close_ready"],c["active_deals"]),"close_ready_to_realized_pct":_rate(c["realized_events"],c["close_ready"])}
def revenue_funnel_tick(state:Dict[str,Any])->Dict[str,Any]:
    cycle=int(state.get("ticks") or 0); truth=canonical_revenue_truth_tick(state); counts=_counts(state,truth); prev=(state.get("revenue_funnel",{}) or {}).get("counts",{}) or {}; deltas={k:counts[k]-int(prev.get(k) or 0) for k in counts}; lane=str(truth.get("recommended_lane") or "demand_discovery"); lm={"opportunity_building":"opportunity","quote_creation":"quote","verification_contact":"contact","demand_discovery":"demand","closing":"close"}; bottleneck={"lane":lm.get(lane,lane),"target_metric":truth.get("target_metric"),"reason":truth.get("reason")}; snap={"version":VERSION,"status":"active","updated_at":utcnow(),"cycle":cycle,"counts":counts,"deltas":deltas,"conversion_rates":_rates(counts),"bottleneck":bottleneck,"canonical_truth_version":truth.get("version"),"truth_rule":"activity_is_not_progress; only canonical evidence-backed stage transitions count as funnel movement"}; hist=list(state.get("revenue_funnel_history",[]) or []); hist.append({"cycle":cycle,"updated_at":snap["updated_at"],"counts":counts,"deltas":deltas,"bottleneck":bottleneck}); state["revenue_funnel_history"]=hist[-MAX_HISTORY:]; state["revenue_funnel"]=snap; return snap
