const VERSION="1.0-agent-economy";
function json(d,s=200){return Response.json(d,{status:s,headers:{"cache-control":"no-store","x-content-type-options":"nosniff","access-control-allow-origin":"*"}});}
function clean(v,n=5000){return String(v??"").trim().replace(/\s+/g," ").slice(0,n);}
function authorized(r,e){const a=clean(e?.OPPORTUNITY_ADMIN_TOKEN,500),b=clean(r.headers.get("x-lumen-admin"),500);return Boolean(a&&b&&a===b);}
async function sha256(text){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(String(text)));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("");}

async function ensure(env){
  if(!env?.DB)return false;
  await env.DB.batch([
    env.DB.prepare("CREATE TABLE IF NOT EXISTS lumen_agent_economy_intents (id TEXT PRIMARY KEY,unique_key TEXT NOT NULL UNIQUE,direction TEXT NOT NULL,kind TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,status TEXT NOT NULL,source_type TEXT NOT NULL,source_id TEXT NOT NULL,opportunity_id TEXT,partner_id TEXT,counterparty_name TEXT,service_name TEXT,amount_usd REAL,currency TEXT NOT NULL DEFAULT 'USD',payment_protocol TEXT,approval_required INTEGER NOT NULL DEFAULT 0,approval_status TEXT NOT NULL DEFAULT 'NOT_REQUIRED',settlement_status TEXT NOT NULL DEFAULT 'UNSETTLED',settled_amount_usd REAL NOT NULL DEFAULT 0,settlement_event_id TEXT,external_execution_allowed INTEGER NOT NULL DEFAULT 0,binding_allowed INTEGER NOT NULL DEFAULT 0,metadata_json TEXT,engine_version TEXT NOT NULL)"),
    env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_lumen_agent_economy_intents_status ON lumen_agent_economy_intents(direction,status,updated_at)"),
    env.DB.prepare("CREATE TABLE IF NOT EXISTS lumen_agent_economy_contract_drafts (id TEXT PRIMARY KEY,intent_id TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,status TEXT NOT NULL,partner_id TEXT NOT NULL,partner_name TEXT NOT NULL,opportunity_id TEXT,service_name TEXT NOT NULL,amount_usd REAL NOT NULL,currency TEXT NOT NULL DEFAULT 'USD',eta_hours REAL,terms_text TEXT,approval_required INTEGER NOT NULL DEFAULT 1,external_message_sent INTEGER NOT NULL DEFAULT 0,binding_allowed INTEGER NOT NULL DEFAULT 0,spend_allowed INTEGER NOT NULL DEFAULT 0,engine_version TEXT NOT NULL)"),
    env.DB.prepare("CREATE TABLE IF NOT EXISTS lumen_agent_economy_ledger (id TEXT PRIMARY KEY,created_at TEXT NOT NULL,entry_type TEXT NOT NULL,direction TEXT NOT NULL,intent_id TEXT,source_event_id TEXT UNIQUE,amount_usd REAL NOT NULL,currency TEXT NOT NULL DEFAULT 'USD',status TEXT NOT NULL,evidence TEXT,engine_version TEXT NOT NULL)"),
    env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_lumen_agent_economy_ledger_type ON lumen_agent_economy_ledger(entry_type,created_at)")
  ]);
  return true;
}

async function syncIncomeOffers(env){
  let rows=[];try{const r=await env.DB.prepare("SELECT p.proposal_id,p.opportunity_id,p.offer_name,p.amount_usd,p.status,p.quality_gate_status,o.name target FROM lumen_proposal_drafts p JOIN lumen_opportunities o ON o.id=p.opportunity_id WHERE p.quality_gate_status='PASS' AND p.amount_usd>0 ORDER BY p.updated_at DESC LIMIT 100").all();rows=r.results||[];}catch{return 0;}
  const now=new Date().toISOString();let n=0;
  for(const r of rows){const key=`income:proposal:${r.proposal_id}`,id=`ECOI-${(await sha256(key)).slice(0,18).toUpperCase()}`;await env.DB.prepare("INSERT INTO lumen_agent_economy_intents(id,unique_key,direction,kind,created_at,updated_at,status,source_type,source_id,opportunity_id,partner_id,counterparty_name,service_name,amount_usd,currency,payment_protocol,approval_required,approval_status,settlement_status,settled_amount_usd,settlement_event_id,external_execution_allowed,binding_allowed,metadata_json,engine_version) VALUES(?,?,'INCOME','SERVICE_OFFER',?,?,'OFFERED_UNSETTLED','proposal',?,?,?,?,?,?,'USD','x402_receive_only',0,'NOT_REQUIRED','UNSETTLED',0,NULL,0,0,?,?) ON CONFLICT(unique_key) DO UPDATE SET updated_at=excluded.updated_at,counterparty_name=excluded.counterparty_name,service_name=excluded.service_name,amount_usd=excluded.amount_usd,metadata_json=excluded.metadata_json,engine_version=excluded.engine_version")
      .bind(id,key,now,now,r.proposal_id,r.opportunity_id,null,r.target||null,r.offer_name||'LUMEN service',Number(r.amount_usd||0),JSON.stringify({proposalStatus:r.status,qualityGateStatus:r.quality_gate_status,countsAsRevenue:false}),VERSION).run();n++;}
  return n;
}

async function syncExpenseProposals(env){
  let rows=[];try{const r=await env.DB.prepare("SELECT c.id case_id,c.opportunity_id,c.title,c.recommended_partner_id,c.recommended_partner_name,n.declared_price_usd,n.eta_hours,n.terms_text,n.trust_level,n.trust_score FROM lumen_negotiation_cases c JOIN lumen_negotiation_candidates n ON n.case_id=c.id AND n.partner_id=c.recommended_partner_id WHERE c.status='READY_FOR_HUMAN_REVIEW' AND n.declared_price_usd IS NOT NULL AND n.declared_price_usd>0 AND n.trust_level='ALLOW' AND n.trust_score>=70 ORDER BY c.commercial_score DESC LIMIT 50").all();rows=r.results||[];}catch{return 0;}
  const now=new Date().toISOString();let n=0;
  for(const r of rows){const key=`expense:negotiation:${r.case_id}:${r.recommended_partner_id}`,id=`ECOO-${(await sha256(key)).slice(0,18).toUpperCase()}`;await env.DB.prepare("INSERT INTO lumen_agent_economy_intents(id,unique_key,direction,kind,created_at,updated_at,status,source_type,source_id,opportunity_id,partner_id,counterparty_name,service_name,amount_usd,currency,payment_protocol,approval_required,approval_status,settlement_status,settled_amount_usd,settlement_event_id,external_execution_allowed,binding_allowed,metadata_json,engine_version) VALUES(?,?,'EXPENSE','PARTNER_SERVICE',?,?,'HUMAN_APPROVAL_REQUIRED','negotiation_case',?,?,?,?,?,?,'USD','x402_or_agreed',1,'PENDING','NOT_PAYABLE',0,NULL,0,0,?,?) ON CONFLICT(unique_key) DO UPDATE SET updated_at=excluded.updated_at,counterparty_name=excluded.counterparty_name,service_name=excluded.service_name,amount_usd=excluded.amount_usd,approval_required=1,approval_status='PENDING',external_execution_allowed=0,binding_allowed=0,metadata_json=excluded.metadata_json,engine_version=excluded.engine_version")
      .bind(id,key,now,now,r.case_id,r.opportunity_id,r.recommended_partner_id,r.recommended_partner_name,r.title||'Partner service',Number(r.declared_price_usd),JSON.stringify({etaHours:r.eta_hours==null?null:Number(r.eta_hours),termsText:clean(r.terms_text,3000),trustLevel:r.trust_level,trustScore:Number(r.trust_score||0),priceVerified:false}),VERSION).run();
    const draftId=`ECOD-${(await sha256(`draft:${id}`)).slice(0,18).toUpperCase()}`;await env.DB.prepare("INSERT INTO lumen_agent_economy_contract_drafts(id,intent_id,created_at,updated_at,status,partner_id,partner_name,opportunity_id,service_name,amount_usd,currency,eta_hours,terms_text,approval_required,external_message_sent,binding_allowed,spend_allowed,engine_version) VALUES(?,?,?,?,'DRAFT_NONBINDING',?,?,?,?,?,'USD',?,?,1,0,0,0,?) ON CONFLICT(intent_id) DO UPDATE SET updated_at=excluded.updated_at,partner_name=excluded.partner_name,service_name=excluded.service_name,amount_usd=excluded.amount_usd,eta_hours=excluded.eta_hours,terms_text=excluded.terms_text,status='DRAFT_NONBINDING',approval_required=1,external_message_sent=0,binding_allowed=0,spend_allowed=0,engine_version=excluded.engine_version")
      .bind(draftId,id,now,now,r.recommended_partner_id,r.recommended_partner_name,r.opportunity_id,r.title||'Partner service',Number(r.declared_price_usd),r.eta_hours==null?null:Number(r.eta_hours),clean(r.terms_text,4000)||null,VERSION).run();n++;}
  return n;
}

async function syncVerifiedSettlements(env){
  let rows=[];try{const r=await env.DB.prepare("SELECT id,created_at,item_id,amount_usd,evidence FROM lumen_revenue_events WHERE event_type='payment_settled' AND status='verified' ORDER BY created_at ASC LIMIT 500").all();rows=r.results||[];}catch{return 0;}
  let n=0;for(const r of rows){const ledgerId=`ELED-${(await sha256(`revenue:${r.id}`)).slice(0,18).toUpperCase()}`;let intent=null;try{intent=await env.DB.prepare("SELECT id FROM lumen_agent_economy_intents WHERE direction='INCOME' AND source_id=? LIMIT 1").bind(r.item_id||'').first();}catch{}
    await env.DB.prepare("INSERT OR IGNORE INTO lumen_agent_economy_ledger(id,created_at,entry_type,direction,intent_id,source_event_id,amount_usd,currency,status,evidence,engine_version) VALUES(?,?,'VERIFIED_SETTLEMENT','INCOME',?,?,?,'USD','VERIFIED',?,?)")
      .bind(ledgerId,r.created_at||new Date().toISOString(),intent?.id||null,r.id,Number(r.amount_usd||0),clean(r.evidence,2000)||null,VERSION).run();
    if(intent?.id){await env.DB.prepare("UPDATE lumen_agent_economy_intents SET updated_at=?,status='REALIZED_INCOME',settlement_status='VERIFIED_SETTLED',settled_amount_usd=?,settlement_event_id=? WHERE id=?").bind(new Date().toISOString(),Number(r.amount_usd||0),r.id,intent.id).run();}
    n++;}
  return n;
}

export async function recomputeAgentEconomy(env){
  if(!(await ensure(env)))return{ok:false,error:'persistence_unavailable',version:VERSION};
  const incomeOffers=await syncIncomeOffers(env);const expenseProposals=await syncExpenseProposals(env);const verifiedSettlements=await syncVerifiedSettlements(env);
  const s=await economyStatsData(env);
  return{ok:true,version:VERSION,synced:{incomeOffers,expenseProposals,verifiedSettlements},state:s,guardrails:{outgoingBudgetUsd:0,outgoingSpendHardBlocked:true,autonomousOutgoingSpend:false,autonomousPurchase:false,autonomousContract:false,bindingActionsHumanGated:true,verifiedSettlementRequiredForIncome:true}};
}

async function economyStatsData(env){await ensure(env);const r=await env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN direction='INCOME' THEN 1 ELSE 0 END) income_intents,SUM(CASE WHEN direction='EXPENSE' THEN 1 ELSE 0 END) expense_intents,SUM(CASE WHEN direction='INCOME' THEN COALESCE(amount_usd,0) ELSE 0 END) potential_income,SUM(CASE WHEN status='REALIZED_INCOME' THEN COALESCE(settled_amount_usd,0) ELSE 0 END) realized_income,SUM(CASE WHEN direction='EXPENSE' THEN COALESCE(amount_usd,0) ELSE 0 END) proposed_expense,SUM(CASE WHEN direction='EXPENSE' AND approval_status='PENDING' THEN 1 ELSE 0 END) pending_approval FROM lumen_agent_economy_intents").first();const l=await env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN entry_type='VERIFIED_SETTLEMENT' THEN amount_usd ELSE 0 END) verified_income FROM lumen_agent_economy_ledger").first();const d=await env.DB.prepare("SELECT COUNT(*) total,SUM(external_message_sent) sent FROM lumen_agent_economy_contract_drafts").first();return{totalIntents:Number(r?.total||0),incomeIntents:Number(r?.income_intents||0),expenseIntents:Number(r?.expense_intents||0),potentialIncomeUsd:Number(r?.potential_income||0),realizedIncomeUsd:Number(r?.realized_income||0),proposedExpenseUsd:Number(r?.proposed_expense||0),pendingHumanApprovals:Number(r?.pending_approval||0),ledgerEntries:Number(l?.total||0),verifiedLedgerIncomeUsd:Number(l?.verified_income||0),contractDrafts:Number(d?.total||0),contractDraftMessagesSent:Number(d?.sent||0)};}

async function policy(){return json({version:VERSION,name:'LUMEN Agent Economy',mode:'receive_and_account_with_outgoing_spend_hard_blocked',currency:'USD',paymentRails:{inbound:['x402','verified_manual_settlement_event'],outboundPrepared:['x402_or_agreed'],outboundExecutable:false},truthRules:['offer_is_not_revenue','quote_is_not_revenue','expense_proposal_is_not_authorization','only_payment_settled_verified_counts_as_realized_income'],outgoingBudgetUsd:0,outgoingSpendHardBlocked:true,autonomousOutgoingSpend:false,autonomousPurchase:false,autonomousContract:false,bindingActionsHumanGated:true});}

export async function handleAgentEconomy(request,env){const u=new URL(request.url);if(request.method==='GET'&&u.pathname==='/agent-economy/policy')return policy();if(request.method==='GET'&&u.pathname==='/agent-economy/stats')return json({version:VERSION,...await economyStatsData(env),outgoingBudgetUsd:0,outgoingSpendHardBlocked:true,autonomousOutgoingSpend:false,bindingActionsHumanGated:true});if(request.method==='POST'&&u.pathname==='/agent-economy/recompute'){if(!authorized(request,env))return json({ok:false,error:'admin_token_required'},403);return json(await recomputeAgentEconomy(env),202);}if(request.method==='GET'&&u.pathname==='/agent-economy/intents'){if(!authorized(request,env))return json({ok:false,error:'admin_token_required'},403);await ensure(env);const r=await env.DB.prepare("SELECT id,direction,kind,status,source_type,source_id,opportunity_id,partner_id,counterparty_name,service_name,amount_usd,currency,payment_protocol,approval_required,approval_status,settlement_status,settled_amount_usd,external_execution_allowed,binding_allowed,updated_at FROM lumen_agent_economy_intents ORDER BY updated_at DESC LIMIT 200").all();return json({version:VERSION,intents:r.results||[]});}if(request.method==='POST'&&u.pathname==='/agent-economy/outbound/execute')return json({ok:false,error:'outgoing_spend_disabled',outgoingBudgetUsd:0,hardBlocked:true,humanApprovalRequired:true},403);return null;}
