import baseWorker from "./worker-entry.js";
import { handleOpportunityEngine, runOpportunityScan } from "./opportunity-engine.js";
import { handleCommercialIntelligence, runCommercialReassessment } from "./commercial-intelligence.js";
import { handleProposalEngine, prepareTopProposal } from "./proposal-engine.js";
import { handleQualityGate, reviewNextProposal } from "./quality-gate.js";
import { handleA2AOutreach, pollOutstandingResponses, sendNextApproved } from "./a2a-outreach.js";
import { handleFollowupEngine, processFollowupCycle } from "./followup-engine.js";
import { handlePartnerNetwork, runPartnerDiscovery } from "./partner-network.js";
import { handlePartnerCouncilQuality, buildQualityPartnerMatches } from "./partner-council-quality.js";
import { handlePartnerVentureBoard } from "./partner-venture-board.js";
import { handleVentureSuggestionIntake, ingestCouncilVentureSuggestions } from "./venture-suggestion-intake.js";
import { handleVentureCouncil, runVentureCouncil } from "./venture-council-engine.js";
import { handleVenturePeerReview, planVenturePeerReviews } from "./venture-peer-review.js";
import { handleCapabilityGapEngine, recomputeCapabilityGaps } from "./capability-gap-engine.js";
import { handlePartnerMarketplace, syncPartnerMarketplace, reviewMarketplaceInterests } from "./partner-marketplace.js";
import { handlePartnerMarketplacePublicCatalog } from "./partner-marketplace-public-catalog.js";
import { handleReferralNetwork, reviewInboundReferrals, planOutboundReferrals, syncReferralSettlements } from "./referral-network.js";
import { handlePartnerNegotiator, recomputeNegotiator } from "./partner-negotiator.js";
import { handleNegotiatorTermsPlanner, planNegotiationTermRequests } from "./negotiator-terms-planner.js";
import { handleAgentGraph, recomputeAgentGraph } from "./agent-graph.js";
import { handleDynamicTeamEngine, buildDynamicTeams } from "./dynamic-team-engine.js";
import { handleRedundancyEngine, recomputeRedundancy } from "./redundancy-engine.js";
import { handleTrustLayer, recomputeTrust } from "./trust-layer.js";
import { handleUntrustedInputFirewall, sanitizeCouncilInputs, sanitizeDelegationResults } from "./untrusted-input-firewall.js";
import { handleRecruitmentEngine, pollRecruitmentResponses } from "./recruitment-engine.js";
import { handleCouncilReplacement } from "./council-replacement.js";
import { handleCouncilJsonRpcFallback } from "./council-jsonrpc-fallback.js";
import { handleCouncilTransportRecovery } from "./council-transport-recovery.js";
import { handleCouncilContributionQuality, reviewActiveCouncilContributions } from "./council-contribution-quality.js";
import { handleCouncilQualitySynthesis } from "./council-quality-synthesis.js";
import { handleCouncilRoundManager, runCouncilRoundManager } from "./council-round-manager.js";
import { handleDelegationEngine, planLatestSynthesizedCouncil } from "./delegation-engine.js";
import { handleDelegationQualityGate, reviewPendingDelegationTasks } from "./delegation-quality-gate.js";
import { handleDelegationResultQuality, reviewDelegationResults } from "./delegation-result-quality.js";
import { handleTrustedDelegationDispatch } from "./trusted-delegation-dispatch.js";
import { handleDelegationRuntime, pollDelegationTasks } from "./delegation-runtime.js";
import { handleObservedPartnerReputation, recomputeObservedReputation } from "./partner-observed-reputation.js";
import { handleCouncilRuntime, pollCouncilRuntime } from "./council-runtime.js";

export default {
  async fetch(request, env, ctx) {
    const opportunityResponse = await handleOpportunityEngine(request, env); if (opportunityResponse) return opportunityResponse;
    const commercialResponse = await handleCommercialIntelligence(request, env); if (commercialResponse) return commercialResponse;
    const proposalResponse = await handleProposalEngine(request, env); if (proposalResponse) return proposalResponse;
    const qualityResponse = await handleQualityGate(request, env); if (qualityResponse) return qualityResponse;
    const outreachResponse = await handleA2AOutreach(request, env); if (outreachResponse) return outreachResponse;
    const followupResponse = await handleFollowupEngine(request, env); if (followupResponse) return followupResponse;
    const recruitmentResponse = await handleRecruitmentEngine(request, env); if (recruitmentResponse) return recruitmentResponse;
    const councilReplacementResponse = await handleCouncilReplacement(request, env); if (councilReplacementResponse) return councilReplacementResponse;
    const councilJsonRpcResponse = await handleCouncilJsonRpcFallback(request, env); if (councilJsonRpcResponse) return councilJsonRpcResponse;
    const councilRecoveryResponse = await handleCouncilTransportRecovery(request, env); if (councilRecoveryResponse) return councilRecoveryResponse;
    const councilContributionQualityResponse = await handleCouncilContributionQuality(request, env); if (councilContributionQualityResponse) return councilContributionQualityResponse;
    const councilQualitySynthesisResponse = await handleCouncilQualitySynthesis(request, env); if (councilQualitySynthesisResponse) return councilQualitySynthesisResponse;
    const councilRoundResponse = await handleCouncilRoundManager(request, env); if (councilRoundResponse) return councilRoundResponse;
    const delegationResponse = await handleDelegationEngine(request, env); if (delegationResponse) return delegationResponse;
    const delegationQualityResponse = await handleDelegationQualityGate(request, env); if (delegationQualityResponse) return delegationQualityResponse;
    const delegationResultQualityResponse = await handleDelegationResultQuality(request, env); if (delegationResultQualityResponse) return delegationResultQualityResponse;
    const trustedDelegationResponse = await handleTrustedDelegationDispatch(request, env); if (trustedDelegationResponse) return trustedDelegationResponse;
    const delegationRuntimeResponse = await handleDelegationRuntime(request, env); if (delegationRuntimeResponse) return delegationRuntimeResponse;
    const observedReputationResponse = await handleObservedPartnerReputation(request, env); if (observedReputationResponse) return observedReputationResponse;
    const trustResponse = await handleTrustLayer(request, env); if (trustResponse) return trustResponse;
    const firewallResponse = await handleUntrustedInputFirewall(request, env); if (firewallResponse) return firewallResponse;
    const councilRuntimeResponse = await handleCouncilRuntime(request, env); if (councilRuntimeResponse) return councilRuntimeResponse;
    const ventureResponse = await handlePartnerVentureBoard(request, env); if (ventureResponse) return ventureResponse;
    const ventureIntakeResponse = await handleVentureSuggestionIntake(request, env); if (ventureIntakeResponse) return ventureIntakeResponse;
    const ventureCouncilResponse = await handleVentureCouncil(request, env); if (ventureCouncilResponse) return ventureCouncilResponse;
    const venturePeerReviewResponse = await handleVenturePeerReview(request, env); if (venturePeerReviewResponse) return venturePeerReviewResponse;
    const capabilityGapResponse = await handleCapabilityGapEngine(request, env); if (capabilityGapResponse) return capabilityGapResponse;
    const marketplaceCatalogResponse = await handlePartnerMarketplacePublicCatalog(request, env); if (marketplaceCatalogResponse) return marketplaceCatalogResponse;
    const marketplaceResponse = await handlePartnerMarketplace(request, env); if (marketplaceResponse) return marketplaceResponse;
    const referralResponse = await handleReferralNetwork(request, env); if (referralResponse) return referralResponse;
    const negotiatorResponse = await handlePartnerNegotiator(request, env); if (negotiatorResponse) return negotiatorResponse;
    const negotiatorTermsResponse = await handleNegotiatorTermsPlanner(request, env); if (negotiatorTermsResponse) return negotiatorTermsResponse;
    const agentGraphResponse = await handleAgentGraph(request, env); if (agentGraphResponse) return agentGraphResponse;
    const dynamicTeamResponse = await handleDynamicTeamEngine(request, env); if (dynamicTeamResponse) return dynamicTeamResponse;
    const redundancyResponse = await handleRedundancyEngine(request, env); if (redundancyResponse) return redundancyResponse;
    const partnerQualityResponse = await handlePartnerCouncilQuality(request, env); if (partnerQualityResponse) return partnerQualityResponse;
    const partnerResponse = await handlePartnerNetwork(request, env); if (partnerResponse) return partnerResponse;
    return baseWorker.fetch(request, env, ctx);
  },

  async scheduled(controller, env, ctx) {
    ctx.waitUntil((async () => {
      await runOpportunityScan(env, { trigger: "cloudflare_cron", scheduledTime: controller?.scheduledTime || null });
      await runCommercialReassessment(env);
      const scheduledAt = new Date(controller?.scheduledTime || Date.now());
      if (scheduledAt.getUTCHours() % 6 === 0) await runPartnerDiscovery(env, { trigger: "cloudflare_cron", scheduledTime: controller?.scheduledTime || null });
      await recomputeTrust(env, { limit: 6 });
      await buildQualityPartnerMatches(env);
      await pollRecruitmentResponses(env);
      await pollCouncilRuntime(env);
      await reviewActiveCouncilContributions(env);
      await sanitizeCouncilInputs(env);
      const councilRound = await runCouncilRoundManager(env, { force: false });
      const councilExternalMessageSent = Boolean(councilRound?.invite?.sent);
      await planLatestSynthesizedCouncil(env);
      await reviewPendingDelegationTasks(env);
      await pollDelegationTasks(env);
      await reviewDelegationResults(env);
      await sanitizeDelegationResults(env);
      await recomputeObservedReputation(env);
      await ingestCouncilVentureSuggestions(env);
      await runVentureCouncil(env);
      await planVenturePeerReviews(env, { limit: 6 });
      await recomputeCapabilityGaps(env);
      await syncPartnerMarketplace(env);
      await reviewMarketplaceInterests(env);
      await reviewInboundReferrals(env);
      await planOutboundReferrals(env);
      await syncReferralSettlements(env);
      await recomputeNegotiator(env);
      // Missing commercial terms are drafted as requests only. Nothing is sent from this planner.
      await planNegotiationTermRequests(env);
      await recomputeAgentGraph(env);
      await buildDynamicTeams(env);
      await recomputeRedundancy(env);
      await prepareTopProposal(env);
      await reviewNextProposal(env);
      await pollOutstandingResponses(env);
      if (!councilExternalMessageSent) {
        const followup = await processFollowupCycle(env);
        if (!followup?.send?.sent) await sendNextApproved(env, { force: false });
      }
    })());
  }
};