const VERSION="1.0-trust-layer";
const FETCH_TIMEOUT_MS=8000;
function json(d,s=200){return Response.json(d,{status:s,headers:{"cache-control":"no-store","x-content-type-options":"nosniff","access-control-allow-origin":"*"}});}
function clean(v,n=12000){return String(v??"").trim().replace(/\s+/g," ").slice(0,n);}
function authorized(r,e){const a=clean(e?.OPPORTUNITY_ADMIN_TOKEN,500),b=clean(r.headers.get("x-lumen-admin"),500);return Boolean(a&&b&&a===b);}
function clamp(n,min=0,max=100){return Math.max(min,Math.min(max,Number(n)||0));}
function timeout(ms){const c=new AbortController(),t=setTimeout(()=>c.abort("timeout"),ms);return{signal:c.signal,clear:()=>clearTimeout(t)};}
function isHttps(v){try{return new URL(v).protocol==='https:';}catch{return false;}}
function b64uDecode(s){let x=String(s||'').replace(/-/g,'+').replace(/_/g,'/');while(x.length%4)x+='=';const bin=atob(x),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a;}
function b64uEncodeBytes(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function utf8(s){return new TextEncoder().encode(String(s));}
function parseJsonText(bytes){try{return JSON.parse(new TextDecoder().decode(bytes));}catch{return null;}}
function normalizedName(s){return clean(s,500).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function privateHost(host){const h=String(host||'').toLowerCase();if(h==='localhost'||h.endsWith('.local')||h==='::1')return true;if(/^127\./.test(h)||/^10\./.test(h)||/^192\.168\./.test(h))return true;const m=h.match(/^172\.(\d+)\./);if(m&&Number(m[1])>=16&&Number(m[1])<=31)return true;return /^169\.254\./.test(h);}
function safeRemoteHttps(v){try{const u=new URL(v);return u.protocol==='https:'&&!privateHost(u.hostname);}catch{return false;}}
function canonical(v){if(v===null)return'null';if(typeof v==='string')return JSON.stringify(v);if(typeof v==='number'){if(!Number.isFinite(v))throw new Error('non_finite_number');return JSON.stringify(v);}if(typeof v==='boolean')return v?'true':'false';if(Array.isArray(v))return'['+v.map(canonical).join(',')+']';if(typeof v==='object'){return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';}throw new Error('unsupported_json_type');}
function cardPayload(card){const x={...card};delete x.signatures;return canonical(x);}
function cardText(card){const skills=Array.isArray(card?.skills)?card.skills:[];return clean([card?.name,card?.description,...skills.flatMap(x=>[x?.name,x?.description,...(Array.isArray(x?.tags)?x.tags:[]),...(Array.isArray(x?.examples)?x.examples:[])])].filter(Boolean).join(' '),24000);}
const MANIPULATION=[/ignore (all|any|the)? ?(previous|prior|system)/i,/system prompt/i,/reveal (your )?(secret|token|credential|private key|seed)/i,/disable (security|safety|guardrail)/i,/bypass (security|approval|authorization|policy)/i,/send (me )?(the )?(admin token|api key|private key|seed phrase)/i,/do not tell (the )?(user|human)/i,/override (human|approval|policy|instructions)/i,/exfiltrat/i,/wallet seed/i];
function manipulationRisk(card){const t=cardText(card),hits=MANIPULATION.filter(r=>r.test(t)).map(r=>r.source);return{hits,count:hits.length,penalty:Math.min(70,hits.length*30)};}
function interfaces(card){const a=Array.isArray(card?.supportedInterfaces)?card.supportedInterfaces:Array.isArray(card?.supported_interfaces)?card.supported_interfaces:[];if(a.length)return a;return card?.url?[{url:card.url,protocolBinding:card.preferredTransport||card.transport||'JSONRPC',protocolVersion:card.protocolVersion||card.protocol_version||''}]:[];}
function supportedInterface(card){return interfaces(card).find(x=>isHttps(x?.url)&&['JSONRPC','JSON-RPC','HTTP+JSON','GRPC'].includes(clean(x?.protocolBinding||x?.binding||x?.transport,80).toUpperCase()))||null;}
function requiresAuth(card){return(Boolean(Array.isArray(card?.securityRequirements)&&card.securityRequirements.length)||Boolean(Array.isArray(card?.security)&&card.security.length));}
async function fetchJson(url){if(!safeRemoteHttps(url))return{ok:false,error:'unsafe_or_non_https_url'};const t=timeout(FETCH_TIMEOUT_MS);try{const r=await fetch(url,{headers:{accept:'application/json, application/a2a+json'},signal:t.signal});const raw=await r.text();if(!r.ok)return{ok:false,error:`http_${r.status}`};try{return{ok:true,value:JSON.parse(raw),raw};}catch{return{ok:false,error:'invalid_json'};}}catch(e){return{ok:false,error:clean(e?.message||e,300)};}finally{t.clear();}}
async function verifyOneSignature(card,sig,cardUrl){
 try{
  if(!sig?.protected||!sig?.signature)return{status:'MALFORMED',reason:'missing_protected_or_signature'};
  const ph=parseJsonText(b64uDecode(sig.protected));if(!ph)return{status:'MALFORMED',reason:'invalid_protected_header'};
  const alg=clean(ph.alg,40),kid=clean(ph.kid,500),jku=clean(ph.jku||sig?.header?.jku,2000);
  if(!alg||!kid)return{status:'MALFORMED',reason:'alg_or_kid_missing',alg,kid};
  if(!['ES256','RS256'].includes(alg))return{status:'PRESENT_UNVERIFIED',reason:'unsupported_alg',alg,kid};
  if(!jku||!safeRemoteHttps(jku))return{status:'PRESENT_UNVERIFIED',reason:'safe_jku_not_available',alg,kid};
  const jwks=await fetchJson(jku);if(!jwks.ok)return{status:'PRESENT_UNVERIFIED',reason:`jwks_${jwks.error}`,alg,kid,jku};
  const keys=Array.isArray(jwks.value?.keys)?jwks.value.keys:[],jwk=keys.find(k=>String(k?.kid||'')===kid);if(!jwk)return{status:'PRESENT_UNVERIFIED',reason:'kid_not_found',alg,kid,jku};
  let key,params;
  if(alg==='ES256'){key=await crypto.subtle.importKey('jwk',jwk,{name:'ECDSA',namedCurve:'P-256'},false,['verify']);params={name:'ECDSA',hash:'SHA-256'};}
  else {key=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);params={name:'RSASSA-PKCS1-v1_5'};}
  const payload=cardPayload(card),encodedPayload=b64uEncodeBytes(utf8(payload)),input=utf8(`${sig.protected}.${encodedPayload}`),signature=b64uDecode(sig.signature);
  const ok=await crypto.subtle.verify(params,key,signature,input);
  return ok?{status:'VERIFIED',reason:'jws_verified',alg,kid,jku}:{status:'PRESENT_UNVERIFIED',reason:'signature_did_not_verify_with_supported_canonicalization',alg,kid,jku};
 }catch(e){return{status:'PRESENT_UNVERIFIED',reason:`verification_error:${clean(e?.message||e,240)}`};}
}
async function signatureState(card,cardUrl){const sigs=Array.isArray(card?.signatures)?card.signatures:[];if(!sigs.length)return{status:'ABSENT_OPTIONAL',verified:0,total:0,details:[]};const details=[];for(const s of sigs.slice(0,4))details.push(await verifyOneSignature(card,s,cardUrl));const verified=details.filter(x=>x.status==='VERIFIED').length;const malformed=details.filter(x=>x.status==='MALFORMED').length;return{status:verified?'VERIFIED':malformed===details.length?'MALFORMED':'PRESENT_UNVERIFIED',verified,total:sigs.length,details};}

async function ensure(env){if(!env?.DB)return false;await env.DB.batch([
 env.DB.prepare("CREATE TABLE IF NOT EXISTS lumen_partner_trust (partner_id TEXT PRIMARY KEY,name TEXT NOT NULL,card_url TEXT,endpoint TEXT,assessed_at TEXT NOT NULL,trust_score INTEGER NOT NULL,trust_level TEXT NOT NULL,card_fetch_status TEXT NOT NULL,https_card INTEGER NOT NULL,https_endpoint INTEGER NOT NULL,name_coherent INTEGER NOT NULL,endpoint_coherent INTEGER NOT NULL,protocol_supported INTEGER NOT NULL,auth_required INTEGER NOT NULL,signature_status TEXT NOT NULL,signature_verified_count INTEGER NOT NULL,manipulation_hits INTEGER NOT NULL,observed_score INTEGER,observed_confidence INTEGER,runtime_failures INTEGER NOT NULL,low_quality_events INTEGER NOT NULL,reasons_json TEXT NOT NULL,signature_detail_json TEXT,engine_version TEXT NOT NULL)"),
 env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_lumen_partner_trust_level ON lumen_partner_trust(trust_level,trust_score DESC,assessed_at)")
]);return true;}
async function safeFirst(env,sql,bind=[]){try{const q=env.DB.prepare(sql);return bind.length?await q.bind(...bind).first():await q.first();}catch{return null;}}
async function safeAll(env,sql,bind=[]){try{const q=env.DB.prepare(sql),r=bind.length?await q.bind(...bind).all():await q.all();return r.results||[];}catch{return[];}}
function endpointCoherence(card,registered){const reg=clean(registered,2000);if(!reg)return false;for(const i of interfaces(card)){if(clean(i?.url,2000)===reg)return true;try{if(new URL(i?.url).hostname===new URL(reg).hostname)return true;}catch{}}return false;}
async function assessPartner(env,p){
 const reasons=[],httpsCard=isHttps(p.card_url),httpsEndpoint=isHttps(p.endpoint);let score=0,card=null,fetchStatus='NOT_FETCHED';
 if(httpsCard)score+=12;else reasons.push('card_not_https');if(httpsEndpoint)score+=12;else reasons.push('endpoint_not_https');
 const fetched=httpsCard?await fetchJson(p.card_url):{ok:false,error:'card_not_https'};if(fetched.ok){card=fetched.value;fetchStatus='OK';score+=12;}else{fetchStatus=clean(fetched.error,100);reasons.push(`card_fetch:${fetchStatus}`);}
 let nameCoherent=false,endCoherent=false,proto=false,auth=false,sig={status:'ABSENT_OPTIONAL',verified:0,total:0,details:[]},manip={hits:[],count:0,penalty:0};
 if(card){nameCoherent=normalizedName(card.name)===normalizedName(p.name);if(nameCoherent)score+=6;else reasons.push('name_mismatch');endCoherent=endpointCoherence(card,p.endpoint);if(endCoherent)score+=8;else reasons.push('endpoint_registry_drift');const intf=supportedInterface(card);proto=Boolean(intf);if(proto)score+=10;else reasons.push('no_supported_secure_interface');auth=requiresAuth(card);if(auth)reasons.push('authentication_required_public_policy_incompatible');sig=await signatureState(card,p.card_url);if(sig.status==='VERIFIED'){score+=24;reasons.push('agent_card_signature_verified');}else if(sig.status==='MALFORMED'){score-=20;reasons.push('agent_card_signature_malformed');}else if(sig.status==='PRESENT_UNVERIFIED'){score+=2;reasons.push('agent_card_signature_present_not_verified');}else reasons.push('agent_card_signature_absent_optional');manip=manipulationRisk(card);if(manip.count){score-=manip.penalty;reasons.push(`manipulation_signals:${manip.count}`);}}
 const obs=await safeFirst(env,"SELECT score,confidence FROM lumen_partner_observed_reputation WHERE partner_id=? LIMIT 1",[p.id]),conf=Number(obs?.confidence||0),observed=Number(obs?.score||0);if(conf>=30){score+=Math.round((observed-50)*.2);reasons.push(`observed_reputation_applied:${observed}/${conf}`);}else if(conf>0)reasons.push(`observed_reputation_low_confidence:${observed}/${conf}`);
 const runtime=await safeAll(env,"SELECT status FROM lumen_partner_runtime_observations WHERE partner_id=?",[p.id]),runtimeFailures=runtime.filter(x=>['unsupported','failed','incompatible'].includes(String(x.status||'').toLowerCase())).length,lowQuality=runtime.filter(x=>String(x.status||'').toLowerCase()==='low_quality').length;score-=Math.min(30,runtimeFailures*12);score-=Math.min(20,lowQuality*10);if(runtimeFailures)reasons.push(`runtime_failures:${runtimeFailures}`);if(lowQuality)reasons.push(`low_quality_events:${lowQuality}`);
 if(auth)score-=8;score=Math.round(clamp(score));let level=score>=70?'ALLOW':score>=50?'CAUTION':score>=30?'RESTRICTED':'QUARANTINE';if(!httpsCard||!httpsEndpoint||manip.count>=2)level='QUARANTINE';
 const now=new Date().toISOString();await env.DB.prepare("INSERT INTO lumen_partner_trust(partner_id,name,card_url,endpoint,assessed_at,trust_score,trust_level,card_fetch_status,https_card,https_endpoint,name_coherent,endpoint_coherent,protocol_supported,auth_required,signature_status,signature_verified_count,manipulation_hits,observed_score,observed_confidence,runtime_failures,low_quality_events,reasons_json,signature_detail_json,engine_version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(partner_id) DO UPDATE SET name=excluded.name,card_url=excluded.card_url,endpoint=excluded.endpoint,assessed_at=excluded.assessed_at,trust_score=excluded.trust_score,trust_level=excluded.trust_level,card_fetch_status=excluded.card_fetch_status,https_card=excluded.https_card,https_endpoint=excluded.https_endpoint,name_coherent=excluded.name_coherent,endpoint_coherent=excluded.endpoint_coherent,protocol_supported=excluded.protocol_supported,auth_required=excluded.auth_required,signature_status=excluded.signature_status,signature_verified_count=excluded.signature_verified_count,manipulation_hits=excluded.manipulation_hits,observed_score=excluded.observed_score,observed_confidence=excluded.observed_confidence,runtime_failures=excluded.runtime_failures,low_quality_events=excluded.low_quality_events,reasons_json=excluded.reasons_json,signature_detail_json=excluded.signature_detail_json,engine_version=excluded.engine_version").bind(p.id,p.name,p.card_url,p.endpoint,now,score,level,fetchStatus,httpsCard?1:0,httpsEndpoint?1:0,nameCoherent?1:0,endCoherent?1:0,proto?1:0,auth?1:0,sig.status,Number(sig.verified||0),manip.count,obs?observed:null,obs?conf:null,runtimeFailures,lowQuality,JSON.stringify(reasons),JSON.stringify(sig.details),VERSION).run();
 return{partnerId:p.id,name:p.name,trustScore:score,trustLevel:level,signatureStatus:sig.status,signatureVerifiedCount:Number(sig.verified||0),manipulationHits:manip.count,runtimeFailures,lowQualityEvents:lowQuality,reasons};
}
export async function recomputeTrust(env,{limit=8}={}){if(!(await ensure(env)))return{ok:false,error:'persistence_unavailable',version:VERSION};const rows=await safeAll(env,"SELECT p.id,p.name,p.card_url,p.endpoint FROM lumen_partner_agents p LEFT JOIN lumen_partner_trust t ON t.partner_id=p.id WHERE p.status IN ('candidate','strong_candidate','watch') ORDER BY CASE WHEN t.partner_id IS NULL THEN 0 ELSE 1 END,t.assessed_at ASC,p.reputation_score DESC LIMIT ?",[Math.max(1,Math.min(12,Number(limit)||8))]),results=[];for(const p of rows)results.push(await assessPartner(env,p));return{ok:true,version:VERSION,assessed:results.length,results,policy:{unsignedCardsAllowed:true,verifiedSignaturesIncreaseTrust:true,presentButUnverifiedSignaturesDoNotClaimValidity:true,manipulationSignalsCanQuarantine:true,privateJwksHostsBlocked:true,autonomousSpend:false}};}
async function stats(env){await ensure(env);const r=await env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN trust_level='ALLOW' THEN 1 ELSE 0 END) allow,SUM(CASE WHEN trust_level='CAUTION' THEN 1 ELSE 0 END) caution,SUM(CASE WHEN trust_level='RESTRICTED' THEN 1 ELSE 0 END) restricted,SUM(CASE WHEN trust_level='QUARANTINE' THEN 1 ELSE 0 END) quarantine,SUM(CASE WHEN signature_status='VERIFIED' THEN 1 ELSE 0 END) verified_signatures,SUM(manipulation_hits) manipulation_hits FROM lumen_partner_trust").first();return json({version:VERSION,totalAssessed:Number(r?.total||0),allow:Number(r?.allow||0),caution:Number(r?.caution||0),restricted:Number(r?.restricted||0),quarantine:Number(r?.quarantine||0),verifiedSignatures:Number(r?.verified_signatures||0),manipulationHits:Number(r?.manipulation_hits||0),unsignedCardsAllowed:true,autonomousSpend:false,bindingActionsHumanGated:true});}
export async function handleTrustLayer(request,env){const u=new URL(request.url);if(request.method==='GET'&&u.pathname==='/trust/stats')return stats(env);if(request.method==='POST'&&u.pathname==='/trust/recompute'){if(!authorized(request,env))return json({ok:false,error:'admin_token_required'},403);let b={};try{b=await request.json();}catch{}return json(await recomputeTrust(env,{limit:Number(b?.limit||8)}),202);}if(request.method==='GET'&&u.pathname==='/trust/partners'){if(!authorized(request,env))return json({ok:false,error:'admin_token_required'},403);await ensure(env);const r=await env.DB.prepare("SELECT * FROM lumen_partner_trust ORDER BY CASE trust_level WHEN 'QUARANTINE' THEN 0 WHEN 'RESTRICTED' THEN 1 WHEN 'CAUTION' THEN 2 ELSE 3 END,trust_score ASC LIMIT 100").all();return json({version:VERSION,partners:(r.results||[]).map(x=>({...x,reasons:parse(x.reasons_json,[]),signatureDetails:parse(x.signature_detail_json,[])}))});}return null;}
